config/routes.rb
TfaServer::Application.routes.draw do
  get "static_pages/home"
  post 'users/sign_in' => 'users#sign_in'

  resources :users

  resources :corporates

  root 'static_pages#home'

end

app/models/corporate.rb
class Corporate < ActiveRecord::Base

  has_many :user
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :corporate

  def self.sign_in(received_user_id, corporate_id, otp)

    # Check corporate ID
    begin
      corporate = Corporate.find(corporate_id)
    rescue
      return { result: 0, message: "Corporate ID is incorrect." }
    end

    # Decrypt OTP
    unescaped_otp = URI.decode(otp).gsub "\\n","\n"
    begin
      plain = AES.decrypt(unescaped_otp, corporate.key)
    rescue Exception => e
      return { result: 0, message: "Could not decrypt OTP because of OTP or passcode is incorrect." }
    end
    splitted = plain.split(",")
    decrypted_user_id = splitted[0].to_i
    nonce = splitted[1].to_i
    passcode = splitted[2]

    # Check received user ID must be the same as in the OTP
    begin
      received_user = User.find(received_user_id)
      puts "*** received_user.id = "+received_user.id.to_s
      puts "*** decrypted_user_id = "+decrypted_user_id.to_s
      if received_user.id != decrypted_user_id
        return { result: 0, message: "Incorrect OTP for this user."} 
      end
    rescue Exception => e
      puts $!
      return { result: 0, message: "Error in user in OTP."}
    end

    target_user = User.find(decrypted_user_id)
    # Check whether received decrypted user_id is consistent with received corporate_id
    if target_user.corporate.id == corporate.id
      # Check whether received passcode is valid
      if (target_user.passcode == passcode)
        # Generate a new passcode
        new_passcode = Digest::SHA1.hexdigest(passcode+rand(2**128).to_s(16))
        target_user.passcode = new_passcode
        target_user.save

        new_nonce = nonce+1
        new_plain = decrypted_user_id.to_s+","+new_nonce.to_s+","+new_passcode
        new_otp = AES.encrypt(new_plain, corporate.key)

        return { result: 1, otp: new_otp }
      else
        return { result: 0, message: 'Incorrect passcode for this user and corporate.' }
      end
    else
      return { result: 0, message: 'Decrypted corporate ID and user ID are inconsistent.' }
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
end

app/controllers/corporates_controller.rb
class CorporatesController < ApplicationController
  before_action :set_corporate, only: [:show, :edit, :update, :destroy]

  # GET /corporates
  # GET /corporates.json
  def index
    @corporates = Corporate.all
  end

  # GET /corporates/1
  # GET /corporates/1.json
  def show
  end

  # GET /corporates/new
  def new
    @corporate = Corporate.new
  end

  # GET /corporates/1/edit
  def edit
  end

  # POST /corporates
  # POST /corporates.json
  def create
    @corporate = Corporate.new(corporate_params)

    respond_to do |format|
      if @corporate.save
        format.html { redirect_to @corporate, notice: 'Corporate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @corporate }
      else
        format.html { render action: 'new' }
        format.json { render json: @corporate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corporates/1
  # PATCH/PUT /corporates/1.json
  def update
    respond_to do |format|
      if @corporate.update(corporate_params)
        format.html { redirect_to @corporate, notice: 'Corporate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @corporate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporates/1
  # DELETE /corporates/1.json
  def destroy
    @corporate.destroy
    respond_to do |format|
      format.html { redirect_to corporates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corporate
      @corporate = Corporate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corporate_params
      params.require(:corporate).permit(:id, :name, :status, :key)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def sign_in
    if params[:user_id].nil? or params[:corp_id].nil? or params[:otp].nil?
      @result = { result: 0, message: "Not enough parameters." } 
    else
    # puts "***"+params[:otp]
      @result = User.sign_in(params[:user_id], params[:corp_id], params[:otp])
    end
    # puts "###"+@result.to_json
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :corporate_id, :passcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/corporates/_form.html.erb
<%= form_for(@corporate) do |f| %>
  <% if @corporate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corporate.errors.count, "error") %> prohibited this corporate from being saved:</h2>

      <ul>
      <% @corporate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corporates/edit.html.erb
<h1>Editing corporate</h1>

<%= render 'form' %>

<%= link_to 'Show', @corporate %> |
<%= link_to 'Back', corporates_path %>

app/views/corporates/index.html.erb
<h1>Listing corporates</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Status</th>
      <th>Key</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @corporates.each do |corporate| %>
      <tr>
        <td><%= corporate.id %></td>
        <td><%= corporate.name %></td>
        <td><%= corporate.status %></td>
        <td><%= corporate.key %></td>
        <td><%= link_to 'Show', corporate %></td>
        <td><%= link_to 'Edit', edit_corporate_path(corporate) %></td>
        <td><%= link_to 'Destroy', corporate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corporate', new_corporate_path %>

app/views/corporates/new.html.erb
<h1>New corporate</h1>

<%= render 'form' %>

<%= link_to 'Back', corporates_path %>

app/views/corporates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @corporate.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @corporate.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @corporate.status %>
</p>

<p>
  <strong>Key:</strong>
  <%= @corporate.key %>
</p>

<%= link_to 'Edit', edit_corporate_path(@corporate) %> |
<%= link_to 'Back', corporates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TfaServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<%= yield %>

app/views/static_pages/home.html.erb
<h1>2nd factor authentication server</h1>
<ul>
<li><a href="/corporates">Manage corporates</a></li>
<li><a href="/users">Manage users</a></li>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :corporate_id %><br>
    <%= f.number_field :corporate_id %>
  </div>
  <div class="field">
    <%= f.label :passcode %><br>
    <%= f.text_field :passcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Corporate</th>
      <th>Passcode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.corporate_id %></td>
        <td><%= user.passcode %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Corporate:</strong>
  <%= @user.corporate_id %>
</p>

<p>
  <strong>Passcode:</strong>
  <%= @user.passcode %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_in.html.erb
<%= raw @result.to_json %>